{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.wagyourtail.unimined",
    "module": "unimined",
    "version": "1.3.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "unimined-1.3.10-SNAPSHOT.jar",
          "url": "unimined-1.3.10-SNAPSHOT.jar",
          "size": 9630581,
          "sha512": "896d3262107dfaba9e13b4e037d47473df7674424ce5fe8fe7d02015094e3d954890d230b42371b036330069b7789447d54fe5d9c82659e5c5af2b346a157f67",
          "sha256": "049bccb35fe5aa4d27d57c3ab30c9e0cca9a0a1cbb25fa4bcd38a4fe9a86e324",
          "sha1": "44301a91891b93fb79dfeaaa7ab6de1e3d719297",
          "md5": "8b9c5814113639722f2c740f2b1356e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.8.7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.3.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations-java5",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "binarypatcher",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "commons-io",
              "module": "*"
            }
          ]
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "9.0.3"
          },
          "excludes": [
            {
              "group": "org.apache.logging.log4j",
              "module": "*"
            },
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.13.2.202306221912-r"
          }
        },
        {
          "group": "com.github.javakeyring",
          "module": "java-keyring",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "net.raphimc",
          "module": "MinecraftAuth",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "unimined-1.3.10-SNAPSHOT.jar",
          "url": "unimined-1.3.10-SNAPSHOT.jar",
          "size": 9630581,
          "sha512": "896d3262107dfaba9e13b4e037d47473df7674424ce5fe8fe7d02015094e3d954890d230b42371b036330069b7789447d54fe5d9c82659e5c5af2b346a157f67",
          "sha256": "049bccb35fe5aa4d27d57c3ab30c9e0cca9a0a1cbb25fa4bcd38a4fe9a86e324",
          "sha1": "44301a91891b93fb79dfeaaa7ab6de1e3d719297",
          "md5": "8b9c5814113639722f2c740f2b1356e7"
        }
      ]
    }
  ]
}
