{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-launcher",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.raphimc",
          "module": "MinecraftAuth",
          "version": {
            "requires": "4.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-2.1.0-dev.jar",
          "url": "headlessmc-launcher-2.1.0-dev.jar",
          "size": 3821074,
          "sha512": "97c60cc1968b155180c3e331a9d9bc9a6d11c66ac2c213133b5ea4dff1b937cbeea8e9159ecd72eb37050ed09fe8b5f6c2e28751d028254007ad39b3ee3d3e04",
          "sha256": "375cd443971ce17ef5164c805b4852dc7e8ae5a6658256de16bcd4681d92e460",
          "sha1": "4acddd079bc24c499ac42f497c3a3207a02de665",
          "md5": "455e2268e7c9d03b069b68e016becc90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.raphimc",
          "module": "MinecraftAuth",
          "version": {
            "requires": "4.1.1-SNAPSHOT"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-2.1.0-dev.jar",
          "url": "headlessmc-launcher-2.1.0-dev.jar",
          "size": 3821074,
          "sha512": "97c60cc1968b155180c3e331a9d9bc9a6d11c66ac2c213133b5ea4dff1b937cbeea8e9159ecd72eb37050ed09fe8b5f6c2e28751d028254007ad39b3ee3d3e04",
          "sha256": "375cd443971ce17ef5164c805b4852dc7e8ae5a6658256de16bcd4681d92e460",
          "sha1": "4acddd079bc24c499ac42f497c3a3207a02de665",
          "md5": "455e2268e7c9d03b069b68e016becc90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-2.1.0-sources.jar",
          "url": "headlessmc-launcher-2.1.0-sources.jar",
          "size": 139297,
          "sha512": "0ae44fe10171b53239886108f93483f3854ff5d8893bc94580d39619fab192eb0b474f318ff91b17300bab4ad4af97a66944d56b7c4124d08c5c13a2a7576d5e",
          "sha256": "1b7e5608e21bb39ee9c1f3096fdf3f24e9204ddcfebd0900cdabbc64f04a9c28",
          "sha1": "5ea2648bd41441faafb333a3c6554c74624fca8e",
          "md5": "0f8ce5567d9fbe0edadb45dfc4e24606"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-2.1.0-javadoc.jar",
          "url": "headlessmc-launcher-2.1.0-javadoc.jar",
          "size": 875774,
          "sha512": "9a1e77e98aa0a2e76b6e19a9441e624c7f04069758d415c1a2dbc1ec674cc4c7729323a4e9738e7bb2cfba5ff949a4bff0f4f7a9280e06d3e29d4cb76284eea5",
          "sha256": "68b927597041fc5a3b0a13ce8568989c3f0eb76d13b431cc3703d953d727ba18",
          "sha1": "057791a20777f8c82aa2b06e4c97e6af97a026b1",
          "md5": "4f3efe6de7906740a0344f02d440986c"
        }
      ]
    }
  ]
}
