{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-web-plugin",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-web-plugin-2.1.0-dev.jar",
          "url": "headlessmc-web-plugin-2.1.0-dev.jar",
          "size": 29082,
          "sha512": "0ccf70d79133400348f7292e1d5a16cadd7fb153b953c4fd0694d6bf54268e784d396506b157258f368c31e0bf73472ef73cf5be0c0a98a418297df4bad527d3",
          "sha256": "4c8c51a57997a96728e4b8db16e4006eddc292961738ef34f3bc90a2ca357148",
          "sha1": "84f92e6d443acfb47c9392076a2fd4b7d2708d4c",
          "md5": "4db1875f68f486ba2f3515bcf8f28b0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-runtime",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "headlessmc-web-plugin-2.1.0-dev.jar",
          "url": "headlessmc-web-plugin-2.1.0-dev.jar",
          "size": 29082,
          "sha512": "0ccf70d79133400348f7292e1d5a16cadd7fb153b953c4fd0694d6bf54268e784d396506b157258f368c31e0bf73472ef73cf5be0c0a98a418297df4bad527d3",
          "sha256": "4c8c51a57997a96728e4b8db16e4006eddc292961738ef34f3bc90a2ca357148",
          "sha1": "84f92e6d443acfb47c9392076a2fd4b7d2708d4c",
          "md5": "4db1875f68f486ba2f3515bcf8f28b0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-web-plugin-2.1.0-sources.jar",
          "url": "headlessmc-web-plugin-2.1.0-sources.jar",
          "size": 11937,
          "sha512": "639a4bec04dbfc63169663f9b1bdd64120d452551eab5c84ce7fb6f071c92b67bce38c526272e43becb6107fa6eebbb43a93f100c9e5215e9dc4b37e4e2f6c6f",
          "sha256": "9d7a9d646ff0edfd80656ea83eab9371c438fc9f360f17c11b2678d3078aa192",
          "sha1": "92a070435ba71b905612f6c639b551bc90d8eeed",
          "md5": "e3692fe864ca4123d70bf44ebab4b1d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-web-plugin-2.1.0-javadoc.jar",
          "url": "headlessmc-web-plugin-2.1.0-javadoc.jar",
          "size": 141960,
          "sha512": "95ab42626245a6d3bf1bb548109788e32342d266bbe0a19b33d4976256fb97458a3cdc1e23027db7ef218e8cdc1cf5cdfbdb1f5d3150cf2b54ff1ef7321aaf3c",
          "sha256": "d71a8930fd1ebae042d0f2024b367fc3003d59e7beb307c4ca44328114f3fad1",
          "sha1": "2f60d0c862d0a5c614713406155912a6fd407892",
          "md5": "6fa2d56d404a989dca5420514930f6f3"
        }
      ]
    }
  ]
}
