{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-runtime",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-runtime-2.1.0-dev.jar",
          "url": "headlessmc-runtime-2.1.0-dev.jar",
          "size": 44626,
          "sha512": "fcb99f28345cd77d9a04207f691121a93206f28275725af04fcd55043ecaaf02c5b6a55c045de63c39c2e614478d89a8cb14a13e648da6d84343b9e8110bdad8",
          "sha256": "5987c07ed936bf8fe558068ebec2110d00a78b9bf8f033ff346d252c65ead24f",
          "sha1": "2c07eb8a9f48ac3ab6c7b9af5a65162988737b4a",
          "md5": "54563ad216644bddf77675bbea28293c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-runtime-2.1.0-dev.jar",
          "url": "headlessmc-runtime-2.1.0-dev.jar",
          "size": 44626,
          "sha512": "fcb99f28345cd77d9a04207f691121a93206f28275725af04fcd55043ecaaf02c5b6a55c045de63c39c2e614478d89a8cb14a13e648da6d84343b9e8110bdad8",
          "sha256": "5987c07ed936bf8fe558068ebec2110d00a78b9bf8f033ff346d252c65ead24f",
          "sha1": "2c07eb8a9f48ac3ab6c7b9af5a65162988737b4a",
          "md5": "54563ad216644bddf77675bbea28293c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-runtime-2.1.0-sources.jar",
          "url": "headlessmc-runtime-2.1.0-sources.jar",
          "size": 21507,
          "sha512": "a1506e15013cec2c713a4f8d5a14e38e10d72b9375d4be541d0664e737233bd5c672569ceecda7766e1223760e621e5da809613bdf47b6c3dd358bf16e7ee35c",
          "sha256": "740741a89207dbd7093e0724998cf4a918461eb297d3de224a6ac144706eaa2a",
          "sha1": "fb9f621b61bc6159dfc24f24be0374db50a15091",
          "md5": "d33d82e248df2ff700d4974e97a04659"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-runtime-2.1.0-javadoc.jar",
          "url": "headlessmc-runtime-2.1.0-javadoc.jar",
          "size": 220356,
          "sha512": "345bf48f631133e279ac5a634b0b25651864a1cfb692a61a1840e43c528d45c87b0c7b39ac78244e28cfa26b704458b56d9a56cd16a1e6a38675788306187190",
          "sha256": "fc6b76e54dd819173c294c921a068772fbc7c4cd61aad293ee7b8a544adb380e",
          "sha1": "9c28797a657e93ce44fb4744d3e24a7d0d06631e",
          "md5": "a894b552ecd93f868edcc1cfb49ab1da"
        }
      ]
    }
  ]
}
