{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-lwjgl",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-lwjgl-2.1.0-dev.jar",
          "url": "headlessmc-lwjgl-2.1.0-dev.jar",
          "size": 41672,
          "sha512": "bb1c31b9e4127d147dd042616f74e62a2ea6d9b3da96aeef9382550b6194c16aaad61f0265e382dbf20b0b0ece9975d819ffa779c1e76d02a1913ea766f8040b",
          "sha256": "b051c97a04ce3329e985619eb01e52f1ad5b36a2f9fc86c7d77af8761567af8b",
          "sha1": "c065255870f873f7ce2c8e2fa26bc11b99c745df",
          "md5": "fb0293c016c7d9a07ac1c073cb33fdec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-lwjgl-2.1.0-dev.jar",
          "url": "headlessmc-lwjgl-2.1.0-dev.jar",
          "size": 41672,
          "sha512": "bb1c31b9e4127d147dd042616f74e62a2ea6d9b3da96aeef9382550b6194c16aaad61f0265e382dbf20b0b0ece9975d819ffa779c1e76d02a1913ea766f8040b",
          "sha256": "b051c97a04ce3329e985619eb01e52f1ad5b36a2f9fc86c7d77af8761567af8b",
          "sha1": "c065255870f873f7ce2c8e2fa26bc11b99c745df",
          "md5": "fb0293c016c7d9a07ac1c073cb33fdec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-lwjgl-2.1.0-sources.jar",
          "url": "headlessmc-lwjgl-2.1.0-sources.jar",
          "size": 24195,
          "sha512": "8a7a51a846c6b97ab17232a7a43ef2c1b0807dfc25d17c0c31361f96f9975d6debf0d3b57a697d064fd887e61df1dbc84d86264dddc9225a7936ab8055ea687b",
          "sha256": "fbcf2e09d0453d08d69f8b00f860fae6351ce55fe25d81817f983efc2343cc71",
          "sha1": "f6982ac200e1e39f42cf133478546e9c351825b2",
          "md5": "fdfe18066c737b95d02f20bd2a06cfdb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-lwjgl-2.1.0-javadoc.jar",
          "url": "headlessmc-lwjgl-2.1.0-javadoc.jar",
          "size": 244564,
          "sha512": "dc375ae8f70ec13e98feceeeeeee6d9d4d858b851bfa33b8ffb8624df5198689145f2ceace1150f8a26665eb9f89b2b60eadbe4561f03d73695d7d8a2269f746",
          "sha256": "ff1c7dc871551a9d3c3ca97d8127971935ae94be22f0aa4b2a7cd19b83752532",
          "sha1": "edb17170a9fbfbfa18baba6e3d39cce36f63eff8",
          "md5": "8249aca9edcbd1882291b6c1254ae843"
        }
      ]
    }
  ]
}
