{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-launcher-jfx",
    "version": "2.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.6.2-dev.jar",
          "url": "headlessmc-launcher-jfx-2.6.2-dev.jar",
          "size": 469,
          "sha512": "89ac4140e464ad911b8ca1ce5e1e0a539bf8e69c66774d151d76fd6e6eecf4f76cc9d936c7a1ebc72c4273c91ff7c25c3fc7900e92bee937bd11b5beaf779043",
          "sha256": "2e43e579369c7177dd71b59f8e2abfa7725756ad23de9c4187a25d940dd05383",
          "sha1": "86248c78f58262375e6dd4ab231a7cbd93da5362",
          "md5": "da82c2c144687ee3f343be6a25c7e24f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.6.2-dev.jar",
          "url": "headlessmc-launcher-jfx-2.6.2-dev.jar",
          "size": 469,
          "sha512": "89ac4140e464ad911b8ca1ce5e1e0a539bf8e69c66774d151d76fd6e6eecf4f76cc9d936c7a1ebc72c4273c91ff7c25c3fc7900e92bee937bd11b5beaf779043",
          "sha256": "2e43e579369c7177dd71b59f8e2abfa7725756ad23de9c4187a25d940dd05383",
          "sha1": "86248c78f58262375e6dd4ab231a7cbd93da5362",
          "md5": "da82c2c144687ee3f343be6a25c7e24f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.6.2-sources.jar",
          "url": "headlessmc-launcher-jfx-2.6.2-sources.jar",
          "size": 261,
          "sha512": "9818d5c0a7cabaf708833aaf905a600968a823241e2a855f04ab99351b42854baecdf02a5bb16f8eeb4a4dbd92c477025285915e3774512cf39abca1c0f96d27",
          "sha256": "cb71aaf70a222cbe57462766efd48a1ced7ea2c8f3d20202df0d7b1768fd8f87",
          "sha1": "203ff0668c5cdf285444f9f7e33a648baf97745b",
          "md5": "d79a08e498ecb545ea3d9a2050ea05ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.6.2-javadoc.jar",
          "url": "headlessmc-launcher-jfx-2.6.2-javadoc.jar",
          "size": 261,
          "sha512": "2c8d6980635d7cada77c523f668c3e930caddb5e28edcef1642618e06df33bc740b407f81574b43a0feb0393a22fe1a675e2b89e617a0c1ee90f312f478d5358",
          "sha256": "d9f8008fc31e75d33572e6a619f49c6cf92f3ced2cbec1963660527bd4533c98",
          "sha1": "c63b99fa9c174e86902e3e276af32a426f01fe2d",
          "md5": "e3534d8986b3e1511130738f14e3a659"
        }
      ]
    }
  ]
}
