{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-jline",
    "version": "2.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-SNAPSHOT-dev.jar",
          "url": "headlessmc-jline-2.1.0-SNAPSHOT-dev.jar",
          "size": 7772,
          "sha512": "f2e2be9db6b62d56c88524acac3fe5964c7c90da4fdc9914cf7b3c6524b277bdf77d255f57ba263c7ebd80886382a02764ae788d22c730f06c37bd93a469cf7d",
          "sha256": "775a5ce3e60452bba876074799233985e498687e5c87a24272ae1e25a00a2f91",
          "sha1": "da58073876fc7d01498c727f6f5d88a880bc415b",
          "md5": "0e323776d8477cac212523905048fe04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-SNAPSHOT-dev.jar",
          "url": "headlessmc-jline-2.1.0-SNAPSHOT-dev.jar",
          "size": 7772,
          "sha512": "f2e2be9db6b62d56c88524acac3fe5964c7c90da4fdc9914cf7b3c6524b277bdf77d255f57ba263c7ebd80886382a02764ae788d22c730f06c37bd93a469cf7d",
          "sha256": "775a5ce3e60452bba876074799233985e498687e5c87a24272ae1e25a00a2f91",
          "sha1": "da58073876fc7d01498c727f6f5d88a880bc415b",
          "md5": "0e323776d8477cac212523905048fe04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-SNAPSHOT-sources.jar",
          "url": "headlessmc-jline-2.1.0-SNAPSHOT-sources.jar",
          "size": 3977,
          "sha512": "3107439403670772fa07f534d94259afebcbe136a51d5ccc95d4504974036664a560082968e221eea311611d5be83d9473c213c23c3f61518644d6a1d7e0aed4",
          "sha256": "8f17f5fe45ff126a901e959c2574b5f8cd2e52c8c38ce7bd4d4ea81dd677df30",
          "sha1": "994d4dce98d9c29d70a51523a6e2845b699438e4",
          "md5": "138393d5a27aaa35516f02d4aaf45886"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-SNAPSHOT-javadoc.jar",
          "url": "headlessmc-jline-2.1.0-SNAPSHOT-javadoc.jar",
          "size": 107465,
          "sha512": "19a60e1cf74d15a730a6ab385e148c0ebe7a9faad5e4dbb2f249bf0efc64b3bfd5a4e2b21eeaca8b03f01a3f0a5ac1f03117672e690802081097e21375f06e65",
          "sha256": "d06640cb406ce9f5429d9154ce4ee348c4827e4b4d3666cf5f82b0bb27edbe92",
          "sha1": "e8ddd213629563cfcedf6ae120e66e4767b710c8",
          "md5": "8632ee837cf5d2477b99cdf066b8812f"
        }
      ]
    }
  ]
}
