{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-auth",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.raphimc",
          "module": "MinecraftAuth",
          "version": {
            "requires": "4.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-auth-2.1.0-dev.jar",
          "url": "headlessmc-auth-2.1.0-dev.jar",
          "size": 13939,
          "sha512": "873e8da23cb18f5d86d4dc8e40544446c677544c2dffc9f22ada3342a4501a9a2a1f3ef3c913df1570c096f328199fb6b6aecbfe8856e8f0221407faa0f064e1",
          "sha256": "eb8302bfb2cc3db9fab5fdd18a9cb12bd330820d5d866e890fdf194941022a40",
          "sha1": "12b798263de7d0c64352cbaa3fb6631259b886de",
          "md5": "684b44c02547f7069439c790e6ad54e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.raphimc",
          "module": "MinecraftAuth",
          "version": {
            "requires": "4.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-auth-2.1.0-dev.jar",
          "url": "headlessmc-auth-2.1.0-dev.jar",
          "size": 13939,
          "sha512": "873e8da23cb18f5d86d4dc8e40544446c677544c2dffc9f22ada3342a4501a9a2a1f3ef3c913df1570c096f328199fb6b6aecbfe8856e8f0221407faa0f064e1",
          "sha256": "eb8302bfb2cc3db9fab5fdd18a9cb12bd330820d5d866e890fdf194941022a40",
          "sha1": "12b798263de7d0c64352cbaa3fb6631259b886de",
          "md5": "684b44c02547f7069439c790e6ad54e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-auth-2.1.0-sources.jar",
          "url": "headlessmc-auth-2.1.0-sources.jar",
          "size": 4781,
          "sha512": "89951694e13cca6de48f7496db23184c686edbb50d71bf33b297332fdec1cea683a12a79eceeccb44b5bef21ba72f0d19e40e7b016fe7209ccb1fb1eba576c15",
          "sha256": "84a4738d529bc65770443d0f7a7e5d2a62cfdf5fafa4d1b065e3f215fa167c53",
          "sha1": "cd21e314dbb4493f66182679cdd146c88760bb11",
          "md5": "9bbc0f5580b15a8dbc55527daff5befa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-auth-2.1.0-javadoc.jar",
          "url": "headlessmc-auth-2.1.0-javadoc.jar",
          "size": 113643,
          "sha512": "07339c323bbb08fe07d959c5b75cd30b5cdbe355fa54a06dfa76c92e2efdff06984d3c7e5cfb21de4af7eac35a21ec6c4624dd17a8f094ea0c02b1091fc031c0",
          "sha256": "4ae140843311c4ad0f4354c0515fc3d09e6da196496c1d3c6aaebc1b427615ec",
          "sha1": "267c189428304ffa862478a5b7277d3795775818",
          "md5": "e91c9796c829da31e6358f61cba0a20d"
        }
      ]
    }
  ]
}
