{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-modlauncher",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-2.2.0-dev.jar",
          "url": "headlessmc-2.2.0-dev.jar",
          "size": 261,
          "sha512": "8b526b45de8c1db7f49eefeb8a06c0c19a561151821dc78c352bab5766b9e9a455ab3df59349c961787d85853060fd8160d9ec2b9d843e7730e56672ba5e821a",
          "sha256": "82ae6c84a446fe20c3909d6adc512e65bf55cb35407c7bc463f497ead7b0635b",
          "sha1": "3f416446c2af9847aab5cc1ebe9583d6eec2013c",
          "md5": "a2cd3c95fa9af3c463afb47822f16101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-modlauncher",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-runtime",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-2.2.0-dev.jar",
          "url": "headlessmc-2.2.0-dev.jar",
          "size": 261,
          "sha512": "8b526b45de8c1db7f49eefeb8a06c0c19a561151821dc78c352bab5766b9e9a455ab3df59349c961787d85853060fd8160d9ec2b9d843e7730e56672ba5e821a",
          "sha256": "82ae6c84a446fe20c3909d6adc512e65bf55cb35407c7bc463f497ead7b0635b",
          "sha1": "3f416446c2af9847aab5cc1ebe9583d6eec2013c",
          "md5": "a2cd3c95fa9af3c463afb47822f16101"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-2.2.0-sources.jar",
          "url": "headlessmc-2.2.0-sources.jar",
          "size": 261,
          "sha512": "a5d343de543bbc6c4b9601ad2091e2ed33251cf8674f54c97d158a6a954221fd7aba02ec329dc320eaf33edc073e6819ca0df7e40413c910bf5c551bc88718a9",
          "sha256": "f91cbab51498f19ea0772b221b5e9c372ce162d170e14c10142cd966ce73bd00",
          "sha1": "30834821b817961eecc5f9b2dd5e850fa6644d85",
          "md5": "f0aaa52f56408330bd7fff7237ce7133"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-2.2.0-javadoc.jar",
          "url": "headlessmc-2.2.0-javadoc.jar",
          "size": 1143921,
          "sha512": "ee25917eda86abaac36c75066734e7a4a372aef5a7ce9edb99fa7b267f740f0068665da5b4cdec23f2df8a913903e277bae34de82cfc9f6c7319c73f78dec916",
          "sha256": "83dc22a3ce2754a0e55f12f4ac9c56d36659e027726f88a766dc60c80e0dcde8",
          "sha1": "30096f0db69f9c8d9497ae1ca1d22b091222daa0",
          "md5": "07cecd557772c2528031ef3fb9ac4f03"
        }
      ]
    }
  ]
}
