{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-jline",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-dev.jar",
          "url": "headlessmc-jline-2.1.0-dev.jar",
          "size": 7843,
          "sha512": "b031bd45780af0d0dadf52b6bb85217be94eb5baf66991eaf2bba9328c1672390c469e7d552d2a7e99573d5a8299e6b5a5fab9b2982f9a56e48aa15df2ddfb3f",
          "sha256": "c185db88ca5107903898734eaa4c08d46630de6b5176bd5f96cfd3c8140630e4",
          "sha1": "3f5ddd2fec02147e045a3f59b517a702f08bf6bb",
          "md5": "9d95169f8e7cc57964170a92b9cef02d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-dev.jar",
          "url": "headlessmc-jline-2.1.0-dev.jar",
          "size": 7843,
          "sha512": "b031bd45780af0d0dadf52b6bb85217be94eb5baf66991eaf2bba9328c1672390c469e7d552d2a7e99573d5a8299e6b5a5fab9b2982f9a56e48aa15df2ddfb3f",
          "sha256": "c185db88ca5107903898734eaa4c08d46630de6b5176bd5f96cfd3c8140630e4",
          "sha1": "3f5ddd2fec02147e045a3f59b517a702f08bf6bb",
          "md5": "9d95169f8e7cc57964170a92b9cef02d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-sources.jar",
          "url": "headlessmc-jline-2.1.0-sources.jar",
          "size": 4298,
          "sha512": "334b68760ace4f2b50ffd3c991dee43adb7e89a2c983291b6b1d48895d9da900efdbffef1e06672d05ed9fa751607fb05e55685d6967799cf8e71fed4e8d2772",
          "sha256": "329c41381ecda057ea7f0b259c8d7e7565bcd09af7de24bfb81d597abdf2603d",
          "sha1": "0897d58b966608c8aaeeaa31961d21f76be86b30",
          "md5": "f5b8d47743486ab620e409cd147b661c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-jline-2.1.0-javadoc.jar",
          "url": "headlessmc-jline-2.1.0-javadoc.jar",
          "size": 109147,
          "sha512": "0f8c50115e7bfb9289d00d9ccf71dce8a9c50ce2254f5e46c93e9f79ab519524378530a4a7f15acae28eddf4d4791aa290eabd8cd6ac23ee8e32bacf49434c9f",
          "sha256": "e3cfbe8149bb4c00de57acfbf4b8642c3bbbe7d2e4797f874714e476c948a3ca",
          "sha1": "536b3baefc77c4e848681b9ea2c08519ea2f2a61",
          "md5": "42c7556a836f1884bda9d768b77866f2"
        }
      ]
    }
  ]
}
