{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.litarvan",
    "module": "openauth",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "openauth-1.1.5.jar",
          "url": "openauth-1.1.5.jar",
          "size": 49264,
          "sha512": "6d5f3f58258492a480e72c03c8d8738745c747c4be8c69de5cc5138ac8218f78352a3ca5e453741a7d77b39a01e20b971c50d036c6e746ba4468ee2f6bbccce7",
          "sha256": "ef53e4d350b8a7bdefce4028067331c90b9720054679b5bf7e3c240e82887669",
          "sha1": "2149dec2ed2f5520f4c9b93fdb00e7cdcf08bf8c",
          "md5": "4507e88dce937ebb918f3bfdc1c0316f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "openauth-1.1.5.jar",
          "url": "openauth-1.1.5.jar",
          "size": 49264,
          "sha512": "6d5f3f58258492a480e72c03c8d8738745c747c4be8c69de5cc5138ac8218f78352a3ca5e453741a7d77b39a01e20b971c50d036c6e746ba4468ee2f6bbccce7",
          "sha256": "ef53e4d350b8a7bdefce4028067331c90b9720054679b5bf7e3c240e82887669",
          "sha1": "2149dec2ed2f5520f4c9b93fdb00e7cdcf08bf8c",
          "md5": "4507e88dce937ebb918f3bfdc1c0316f"
        }
      ]
    }
  ]
}
