{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-modlauncher",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "headlessmc-modlauncher-2.1.0-dev.jar",
          "url": "headlessmc-modlauncher-2.1.0-dev.jar",
          "size": 9947,
          "sha512": "7bedf520219319735a3d87a808021ce1c6ea00a0650846d91462ddd55213aa1f7398d21ff5c0d9c99c45018a42fc4d08ff1c78c50bfc54e9bab042733168cb01",
          "sha256": "4ecb3e21bd7d62fe40191662cd9b616a2a3ffcf62d6b680cfbc2b7c45ca03bf7",
          "sha1": "5ba8692f3fd3f8a1cd3a59b0b1a0f1b16dd2454e",
          "md5": "f77fc984b5f93d6d56706c784b7e8a0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-modlauncher-2.1.0-dev.jar",
          "url": "headlessmc-modlauncher-2.1.0-dev.jar",
          "size": 9947,
          "sha512": "7bedf520219319735a3d87a808021ce1c6ea00a0650846d91462ddd55213aa1f7398d21ff5c0d9c99c45018a42fc4d08ff1c78c50bfc54e9bab042733168cb01",
          "sha256": "4ecb3e21bd7d62fe40191662cd9b616a2a3ffcf62d6b680cfbc2b7c45ca03bf7",
          "sha1": "5ba8692f3fd3f8a1cd3a59b0b1a0f1b16dd2454e",
          "md5": "f77fc984b5f93d6d56706c784b7e8a0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-modlauncher-2.1.0-sources.jar",
          "url": "headlessmc-modlauncher-2.1.0-sources.jar",
          "size": 6356,
          "sha512": "1e8b6d8d335544726e3c998d356e7a9ed390494599dbd3550f66b75dc67f35ef205f0a2334bb336d74b6ddffa0d80decb3dfc9873b09e91b5166a33b5d5ed9cd",
          "sha256": "f944129c8147b128337ff9eeca1bbee1070ca33c28a370b68ea028fade37829e",
          "sha1": "b6510f86cab911623236bf72b557b96b7a3060f1",
          "md5": "4ac428b223add33517a8c77c4d913cb1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-modlauncher-2.1.0-javadoc.jar",
          "url": "headlessmc-modlauncher-2.1.0-javadoc.jar",
          "size": 102780,
          "sha512": "50ce98fd2f6ebfd90c91ed899ea8fd11c26b61a1c665becf0ba4079ccbbbb4a16e6da6b64ad5ea545641dcd4a30a7ed5b5f821b4976add269ed8b83f880f8e22",
          "sha256": "1dcf06e6745529970da703739328e39072e371046d8a2418caff4dd51cc352b7",
          "sha1": "cfd401bd28e844e69ab084e6c6c89b1740100241",
          "md5": "4845825568b03d9fcf44f54f88093b9b"
        }
      ]
    }
  ]
}
