{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-runtime",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-commons",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-runtime-1.6.3.jar",
          "url": "headlessmc-runtime-1.6.3.jar",
          "size": 92323,
          "sha512": "55b6d947f63f05f6085c9329a34594adc620aa3edf2b1eff5dba3c40d203a2b6f3b29be81d68fedbbeeee14271636a71aa9b088fb356ec91cb2689b41967dacf",
          "sha256": "4d9e2860483e17cc04296d58fbd2b98ad74081fdc91507c1720f416177cd619a",
          "sha1": "a95194ab7dfdf98183c01cf5e6015064a4144bfd",
          "md5": "636e64e9b6238fe865aaa6474b7d4aa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-commons",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-runtime-1.6.3.jar",
          "url": "headlessmc-runtime-1.6.3.jar",
          "size": 92323,
          "sha512": "55b6d947f63f05f6085c9329a34594adc620aa3edf2b1eff5dba3c40d203a2b6f3b29be81d68fedbbeeee14271636a71aa9b088fb356ec91cb2689b41967dacf",
          "sha256": "4d9e2860483e17cc04296d58fbd2b98ad74081fdc91507c1720f416177cd619a",
          "sha1": "a95194ab7dfdf98183c01cf5e6015064a4144bfd",
          "md5": "636e64e9b6238fe865aaa6474b7d4aa9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-runtime-1.6.3-sources.jar",
          "url": "headlessmc-runtime-1.6.3-sources.jar",
          "size": 20142,
          "sha512": "d84c68543a6c11500d300b51aef6a7ccee241679c8ea5cab89aa414ca9024242952627481bbb4d1b1c490dda3a39b9d915718dc5773d5e1d7490ff1ea45e5534",
          "sha256": "dd4217c1a4b5010fff9d3ffd348bff8bec523c39000f620758ab339e625ad181",
          "sha1": "c70710015c9255d3bcc7423e9a5b4ee4ae8d87f7",
          "md5": "06fc1f3889d6e91b4d2b42f796c24f22"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-runtime-1.6.3-javadoc.jar",
          "url": "headlessmc-runtime-1.6.3-javadoc.jar",
          "size": 134713,
          "sha512": "747095e1fb31ca70960571f35be6238db509aeb377d8c2d403bd48b2d771f781b5ab2b5355c6829ddf9fc74d00c71aced902731b0613922a20983e2266abc1c2",
          "sha256": "3d2c82357e510a9163fce25388d8df48b7b770f5acea375460d31e3a527461ad",
          "sha1": "0d6673be35d8f67079ce3cc97d843ac9fb29c57c",
          "md5": "d828d61ed97c21f5d4ffeea2280db9be"
        }
      ]
    }
  ]
}
