{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-logging",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "headlessmc-logging-2.1.0-dev.jar",
          "url": "headlessmc-logging-2.1.0-dev.jar",
          "size": 13336,
          "sha512": "bbfc2f7c083e6cc14c4090e91680e4d90c0e743aad0f4bc40370f21d59074eff2e7454180fe43fd3700c3fd3882feb372af0ecad4d8138e95c13b00998c9e65f",
          "sha256": "b40bc9d7c88e59b9878781b8a631600da6d200fe49f39b2d11a90b8d28936db6",
          "sha1": "4345df3cbbc45b0549800a820ffa5e55eb88b2b2",
          "md5": "568faeebbf7c9e049a91d60a7c7b4766"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-logging-2.1.0-dev.jar",
          "url": "headlessmc-logging-2.1.0-dev.jar",
          "size": 13336,
          "sha512": "bbfc2f7c083e6cc14c4090e91680e4d90c0e743aad0f4bc40370f21d59074eff2e7454180fe43fd3700c3fd3882feb372af0ecad4d8138e95c13b00998c9e65f",
          "sha256": "b40bc9d7c88e59b9878781b8a631600da6d200fe49f39b2d11a90b8d28936db6",
          "sha1": "4345df3cbbc45b0549800a820ffa5e55eb88b2b2",
          "md5": "568faeebbf7c9e049a91d60a7c7b4766"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-logging-2.1.0-sources.jar",
          "url": "headlessmc-logging-2.1.0-sources.jar",
          "size": 7437,
          "sha512": "48f07f22bf8139d075a1f76e595b52cac22c4fcca34546238ca440cd31c70cdb6bd833bb7cc02dcad589ea936deb6b28f70303f4dbb59244784a377899ba13b5",
          "sha256": "d7376770392e8f8ba9a367832c408f2fca6679cd484bce5fc7c0f7a72807d19a",
          "sha1": "4c0805065debec45d3d47f5163b69a0b3328c4e2",
          "md5": "bed1e1cde5c23d0ad96d1a4180a15fa5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-logging-2.1.0-javadoc.jar",
          "url": "headlessmc-logging-2.1.0-javadoc.jar",
          "size": 145629,
          "sha512": "3e861002bd72d0b4c338b452dc3c29306ebd3690aae56eeed677998a66eed5641d56d33b68d8d49f8f03eb289cf469e3f9dcf80a115974da0409a6df8bbe8e08",
          "sha256": "19fe84ea5c82fe65bea9212400283975fdbf2c5f9fd8dc5efc72139068b383e3",
          "sha1": "bb3ad99748784c218c82485b5f76baa9412d6210",
          "md5": "7b2e79248c943b225c7f81b91b2d3b95"
        }
      ]
    }
  ]
}
