{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-api",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-api-2.1.0-dev.jar",
          "url": "headlessmc-api-2.1.0-dev.jar",
          "size": 67360,
          "sha512": "7977d0df32ca500346a4ab27b9487f5560539213db1593069a41abfbe4398a3c02a8de84e3d6eca8bff6682c711f200fd9bbca4f126c1a571b0a63c6d0fb0ec3",
          "sha256": "cdd6457571f95a07f6bce82c20e11a15708117d5c9b804b151b698d08f4780fb",
          "sha1": "13af26198014751648305d230e676aabeea33c2c",
          "md5": "3193552268a1e7e195065ba232e86370"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-api-2.1.0-dev.jar",
          "url": "headlessmc-api-2.1.0-dev.jar",
          "size": 67360,
          "sha512": "7977d0df32ca500346a4ab27b9487f5560539213db1593069a41abfbe4398a3c02a8de84e3d6eca8bff6682c711f200fd9bbca4f126c1a571b0a63c6d0fb0ec3",
          "sha256": "cdd6457571f95a07f6bce82c20e11a15708117d5c9b804b151b698d08f4780fb",
          "sha1": "13af26198014751648305d230e676aabeea33c2c",
          "md5": "3193552268a1e7e195065ba232e86370"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-api-2.1.0-sources.jar",
          "url": "headlessmc-api-2.1.0-sources.jar",
          "size": 40868,
          "sha512": "0f195aa2c47609ea73475ef90d1c340d66fcd4f37dec7aa67304691a4788307b66ef3835eb5581bc5a981ded44f1b5633eb881cdd2853e2d2ff20e2412c64448",
          "sha256": "2b1442c13765c7a5bfddcc059add829b33cfdad85d0cb44a8da7a21a758f2d88",
          "sha1": "845f6e6c8d9cccd4770db6c272903ab8ebfedca0",
          "md5": "55724bdaca431963a8b004ad0fb327ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-api-2.1.0-javadoc.jar",
          "url": "headlessmc-api-2.1.0-javadoc.jar",
          "size": 366310,
          "sha512": "8f65eac5ca7fee1b46dee8007d96863a50088ffa30d0689f73644b851d52ef2414e972be677a3a97a0023b42002d73e2642491cba257280cdf60b90f07c505dd",
          "sha256": "5754d9c61d17b3f9a8dc8089c2e5d4511a597c1f98d12a2e3cf1f8f547eb905d",
          "sha1": "4507a8dfd724a4f9b7df6d1ac9b50c20956e1f4b",
          "md5": "8c75781bd47a88dcbc2c689d5e782cbd"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-api-2.1.0-test-fixtures.jar",
          "url": "headlessmc-api-2.1.0-test-fixtures.jar",
          "size": 5828,
          "sha512": "d1ef891cd54e316429817ea0e3382c8eb6e3635c07488180df28b1f2321a56dd8f08bdcaa638144dbd013cb84fca72762222454b8feda3cf6c7f8ae74b0d9fc9",
          "sha256": "559a151939b64b5c0970e67ce998bb965efca9122b1b4527450a18ba5bb13722",
          "sha1": "b621533673f2b522cd755450799f6f8413757ef8",
          "md5": "9762595f43df5a27441419fdb73b006b"
        }
      ],
      "capabilities": [
        {
          "group": "me.earth.headlessmc",
          "name": "headlessmc-api-test-fixtures",
          "version": "2.1.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-api-2.1.0-test-fixtures.jar",
          "url": "headlessmc-api-2.1.0-test-fixtures.jar",
          "size": 5828,
          "sha512": "d1ef891cd54e316429817ea0e3382c8eb6e3635c07488180df28b1f2321a56dd8f08bdcaa638144dbd013cb84fca72762222454b8feda3cf6c7f8ae74b0d9fc9",
          "sha256": "559a151939b64b5c0970e67ce998bb965efca9122b1b4527450a18ba5bb13722",
          "sha1": "b621533673f2b522cd755450799f6f8413757ef8",
          "md5": "9762595f43df5a27441419fdb73b006b"
        }
      ],
      "capabilities": [
        {
          "group": "me.earth.headlessmc",
          "name": "headlessmc-api-test-fixtures",
          "version": "2.1.0"
        }
      ]
    }
  ]
}
