{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-launcher",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-commons",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-1.6.3.jar",
          "url": "headlessmc-launcher-1.6.3.jar",
          "size": 1057664,
          "sha512": "7f21ab1ae40e0360d11b5b1c5456f4e337d4672971b5a10d5185c804da2a58caf766e0d45ba24bf655bb4adb4be7b56170f629bdf76ef87e237c4db0c0c3ba1f",
          "sha256": "0d4c856089f742ad52fe457e7a7dfbb6e8dc8e04a3703cbdd1e121ad160963fa",
          "sha1": "4239bc533f68a6ab48317390cbe20cd402153d7d",
          "md5": "e99b66623b8768b4e6bab4b9e8f327be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-commons",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "fr.litarvan",
          "module": "openauth",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "net.kunmc.lab",
          "module": "forgecli",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "legacy"
            },
            {
              "group": "*",
              "module": "asm"
            },
            {
              "group": "*",
              "module": "asm-tree"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "forgecli",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-1.6.3.jar",
          "url": "headlessmc-launcher-1.6.3.jar",
          "size": 1057664,
          "sha512": "7f21ab1ae40e0360d11b5b1c5456f4e337d4672971b5a10d5185c804da2a58caf766e0d45ba24bf655bb4adb4be7b56170f629bdf76ef87e237c4db0c0c3ba1f",
          "sha256": "0d4c856089f742ad52fe457e7a7dfbb6e8dc8e04a3703cbdd1e121ad160963fa",
          "sha1": "4239bc533f68a6ab48317390cbe20cd402153d7d",
          "md5": "e99b66623b8768b4e6bab4b9e8f327be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-1.6.3-sources.jar",
          "url": "headlessmc-launcher-1.6.3-sources.jar",
          "size": 92094,
          "sha512": "434cfbabd11dc1eb325473189af178e438b2c7eec55ce8df4f8d8bb9c9b39fb956b947a991dc16909e00ea5778be73a623ab8d2e34145b1cf9802716f62e35b8",
          "sha256": "f387ecf993b02fea5b0b12937f9cb3bb2eec0a7666cd94ebaaa5aa70171565a9",
          "sha1": "f39e3d53c92944d45c508ea0bd26bbf21057d51e",
          "md5": "0f715982a33ca1e3e8b980b43c70cdab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-1.6.3-javadoc.jar",
          "url": "headlessmc-launcher-1.6.3-javadoc.jar",
          "size": 484983,
          "sha512": "cc7f17accc91f91bcbf3e2d0903620a2e03c5dfdec8e98174e5670a5efb313aa4a90a873f83fed62653fab134a53e9e6de372773f5a984b4064bde0af5f4cb6a",
          "sha256": "98676a3f430cc1c7488100bd723d4fe50f57a9e3863da204b9c59a769fdecd0d",
          "sha1": "3a3012292db08b877e00faaf9bc137d535c70a0c",
          "md5": "94576a7951a376077612330e519aeeef"
        }
      ]
    }
  ]
}
