{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-launcher-jfx",
    "version": "2.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-dev.jar",
          "url": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-dev.jar",
          "size": 469,
          "sha512": "a7fd17348e64a49ba6070611476f623888482fc3c4682a0152a220401dd4efb6804e2d50fdfce85ab22d69019baabfd2682b8dd2a7faa3463b0f49ca52aee7dd",
          "sha256": "5825aaaaef9206cd757cd25e83d11d351da06b21d1efaa7ae11b86d55e2f53f4",
          "sha1": "a9863677417a67f389a8c56556d5431aa208405e",
          "md5": "ee26e682c18ef44a5a762cd8a7059053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "17.0.9"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux"
            }
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-dev.jar",
          "url": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-dev.jar",
          "size": 469,
          "sha512": "a7fd17348e64a49ba6070611476f623888482fc3c4682a0152a220401dd4efb6804e2d50fdfce85ab22d69019baabfd2682b8dd2a7faa3463b0f49ca52aee7dd",
          "sha256": "5825aaaaef9206cd757cd25e83d11d351da06b21d1efaa7ae11b86d55e2f53f4",
          "sha1": "a9863677417a67f389a8c56556d5431aa208405e",
          "md5": "ee26e682c18ef44a5a762cd8a7059053"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-sources.jar",
          "url": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-sources.jar",
          "size": 261,
          "sha512": "4fa528ab1aa27d1e60cf4cd7477fa02850052b46969f1564a661f7ec5f20441d39c63d7cb84833d3cba84f22d7bb183b2454980b0788260f14f6aa7d0eb7a21b",
          "sha256": "9b3fefcdd8955933ad2880bb943177bab8e40488b2a458a1baaa8a901532236b",
          "sha1": "d5a0e48bbb3ee103e43d411f3ab3537f2a7cc29a",
          "md5": "0f93cb5bbf43e9dad86901f3551c6ebd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-javadoc.jar",
          "url": "headlessmc-launcher-jfx-2.1.0-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "fa5f3766456e3cdcbe0816b4792ee2296340bf1b91bf48561ecd61d70767ec815da432d51a22a04ad2f637d38ced2f35ec03b8b6d6717320e04978c33bc91611",
          "sha256": "1a2e0bb5dde49e3ffa62c9ffb11989a4f9b4e4831710f4bc78ef8bc53b78fb56",
          "sha1": "d78fb421ee6e38eebd762c28c87767f4a39e94bc",
          "md5": "9036fdce519516b915ee675848472f49"
        }
      ]
    }
  ]
}
