{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-modlauncher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-runtime",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-2.1.0-dev.jar",
          "url": "headlessmc-2.1.0-dev.jar",
          "size": 261,
          "sha512": "1696ab0e63580d4a6e0c49b2dd9b76188ad09d860a3896223d0c843383bfe7eb75bef3e44c46eb43e159e7c7c2e2a38dce7f92e8f1ebe17d8b78385ebf3cc4c8",
          "sha256": "d555317d95c0c69a02f2a1786cae6ed58376955ea33801b2feb2e25a37b61389",
          "sha1": "d49d2927f86347a22c46701c722a1e4591db09be",
          "md5": "867840df839a384e77684981d272c9f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-api",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-auth",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-jline",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-logging",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-modlauncher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-lwjgl",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-runtime",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-2.1.0-dev.jar",
          "url": "headlessmc-2.1.0-dev.jar",
          "size": 261,
          "sha512": "1696ab0e63580d4a6e0c49b2dd9b76188ad09d860a3896223d0c843383bfe7eb75bef3e44c46eb43e159e7c7c2e2a38dce7f92e8f1ebe17d8b78385ebf3cc4c8",
          "sha256": "d555317d95c0c69a02f2a1786cae6ed58376955ea33801b2feb2e25a37b61389",
          "sha1": "d49d2927f86347a22c46701c722a1e4591db09be",
          "md5": "867840df839a384e77684981d272c9f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-2.1.0-sources.jar",
          "url": "headlessmc-2.1.0-sources.jar",
          "size": 261,
          "sha512": "886cd1c4c2209f531c1e4696f2e39e716b2d45853ad8b5d9d0f5db2b34ff8d83beff5a4997f9f3ac6a768a93b058c1736bf9efa66225e3b4d73d61dfb35c42a4",
          "sha256": "3b0e0e639e9e3a8554dac9a81a3122d543ff5de7ae983642393758778361fd46",
          "sha1": "9c199efb234c39c8208fb7394c504fff9fde079d",
          "md5": "5adeb9e2a69bd5271d1090ec7d9aee23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-2.1.0-javadoc.jar",
          "url": "headlessmc-2.1.0-javadoc.jar",
          "size": 1138447,
          "sha512": "5f80be7188d4d50c625e567412576bf7a4355380bba3e4de19149cbb33bd34b5943b703c9082babb25ac6773a9bc3a2eaf7508f2dd4f3583eca0dd2822df0058",
          "sha256": "17245bfa967822d9fd503d78b328cf26faeebc794c8ed648392cdc88431e61a4",
          "sha1": "de71305035f1b97ffdf58853196967092880fcc6",
          "md5": "02999410650da531230ac3f38ea308a1"
        }
      ]
    }
  ]
}
