{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-web",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-web-2.1.0-dev.jar",
          "url": "headlessmc-web-2.1.0-dev.jar",
          "size": 15233265,
          "sha512": "6da8b7e979492f5c53f71657a6f9211996f035144eb8c4171df2f96e73cfdee5777bbc1a6449dab2c248e43877da8435585ee8705ec45e33cf6fd4749e0868be",
          "sha256": "31fbae9af731afa1439cb747391488fa74dc5970b8ea441c735568f195ade5b7",
          "sha1": "b72eb9445d4474e023d24d933aad7b7e7b9d86d1",
          "md5": "91c7cc5e9273f0db2f71985cc36bdaaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-launcher-wrapper",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-web-2.1.0-dev.jar",
          "url": "headlessmc-web-2.1.0-dev.jar",
          "size": 15233265,
          "sha512": "6da8b7e979492f5c53f71657a6f9211996f035144eb8c4171df2f96e73cfdee5777bbc1a6449dab2c248e43877da8435585ee8705ec45e33cf6fd4749e0868be",
          "sha256": "31fbae9af731afa1439cb747391488fa74dc5970b8ea441c735568f195ade5b7",
          "sha1": "b72eb9445d4474e023d24d933aad7b7e7b9d86d1",
          "md5": "91c7cc5e9273f0db2f71985cc36bdaaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-web-2.1.0-sources.jar",
          "url": "headlessmc-web-2.1.0-sources.jar",
          "size": 2127,
          "sha512": "03b8b617fa710aea0577b1c9d5f318eeb33c9b0128c7f1ef8993cc9ba479fa27caff5508deea87813f8bf20089af8482ef5e071895dd27bb5cbe6853fa45a325",
          "sha256": "d54f7596500baa77711406e914735c58e3a2aef051ae91f0f948db0b371df0cf",
          "sha1": "2d5abea5a2a832079ba4ea6e6366958cc12fdb6f",
          "md5": "0e8a1227f64bafe335359df6e45f6f5c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-web-2.1.0-javadoc.jar",
          "url": "headlessmc-web-2.1.0-javadoc.jar",
          "size": 101720,
          "sha512": "b8ebe359fb2499cf6bd72c2a6cb8152fe1de57654c595da0e8e6184438dd65561f237a42558d80fb0e466d0296aa1d82201839d9e98135a627646dcee1a269ba",
          "sha256": "bfcc9fbb549bf87c781aaf623bc0663b175184766bf964886b88a03b347f5e27",
          "sha1": "28541fd0d3ffda8a164d54f81e7889a45969dd80",
          "md5": "47f7fa6a6dd5dd390c2f7765e1b00c4a"
        }
      ]
    }
  ]
}
