{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.pingbypass",
    "module": "pb-client-forge",
    "version": "1.20.4-0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-client",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-api",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-security-api",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-security-lib",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-commons",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "pb-client-forge-1.20.4-0.0.1.jar",
          "url": "pb-client-forge-1.20.4-0.0.1.jar",
          "size": 2879,
          "sha512": "23688c70adb7b6c50345edf34e705179c0f389db7a8ff18f52ff650966d4dc6d4b72fe6b386a3821e264708435e30bf84f92214b73ff75086defa3ae78297b17",
          "sha256": "ea4278f8770db66b9a16e68d09e0d057129248ba6ed51feb0931fcb0406edb3b",
          "sha1": "ebbf7f5d8bf8c159b013c2cdedcaa15164371d7c",
          "md5": "eeba57398efa8db61d53d455f4a0e9c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-client",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-api",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-security-api",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-security-lib",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        },
        {
          "group": "me.earth.pingbypass",
          "module": "pb-commons",
          "version": {
            "requires": "1.20.4-0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "pb-client-forge-1.20.4-0.0.1.jar",
          "url": "pb-client-forge-1.20.4-0.0.1.jar",
          "size": 2879,
          "sha512": "23688c70adb7b6c50345edf34e705179c0f389db7a8ff18f52ff650966d4dc6d4b72fe6b386a3821e264708435e30bf84f92214b73ff75086defa3ae78297b17",
          "sha256": "ea4278f8770db66b9a16e68d09e0d057129248ba6ed51feb0931fcb0406edb3b",
          "sha1": "ebbf7f5d8bf8c159b013c2cdedcaa15164371d7c",
          "md5": "eeba57398efa8db61d53d455f4a0e9c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pb-client-forge-1.20.4-0.0.1-sources.jar",
          "url": "pb-client-forge-1.20.4-0.0.1-sources.jar",
          "size": 1186,
          "sha512": "b0b06fd2056af79d62e66beb1367490bd89c9c6c8efffcdfde0d2941f6011ee11f738c8b5048f577ab4e2f86a79e4d68acd492e28ab5a886ed52912781b2e15c",
          "sha256": "5b611c556169369c1e4f4d48823843298934471b2ebd048a07d4f2a4319c3bf1",
          "sha1": "e936778c5246f06beb64b5f6ea50f4e8c24b3ff8",
          "md5": "501e4af62357eaeb86be1cdee252772b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pb-client-forge-1.20.4-0.0.1-javadoc.jar",
          "url": "pb-client-forge-1.20.4-0.0.1-javadoc.jar",
          "size": 71960,
          "sha512": "fe8a1cab48ec96a4796fe59d766e342478d08ace65e212e112998abb84e46f0fc25d2f297c8c259523be61776e374233f38d3b004503c91982092442f180bcd5",
          "sha256": "ffb73bd7f68d27ba1d9631b82c8b0e18474f3ef1d10a96ef0986f42f90949821",
          "sha1": "246770321b71f97f0e44a46ab308be6abca6ea73",
          "md5": "7b15657da47d3cbfb7006ca975b6e548"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pb-client-forge-1.20.4-0.0.1-fat.jar",
          "url": "pb-client-forge-1.20.4-0.0.1-fat.jar",
          "size": 499573,
          "sha512": "4284c27deb4984f3aa9273846b4257042d18f79c4a74a340ee960f68bb88a88cb091d720284869b9ab1284e6c7a41bce1d347813d9f2ccaf045ece833c541441",
          "sha256": "13976d0d9da37d010b19e272d9aee98bfc995676c046b24ce20b16b621964160",
          "sha1": "107636dc7130d0c9b14078a0fefc4fff665f807e",
          "md5": "bfd0579e1ba86afac6245aaa070b61fb"
        }
      ]
    }
  ]
}
