{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earth.headlessmc",
    "module": "headlessmc-launcher-wrapper",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "headlessmc-launcher-wrapper-2.1.0-dev.jar",
          "url": "headlessmc-launcher-wrapper-2.1.0-dev.jar",
          "size": 8445292,
          "sha512": "059168c0cf927bd867d3690af0998eab8853afca54640be808d131c455edafc1901f3793aa4edb4bedc93cd16905824e316b9aeab444c77d0647150eb14dbf71",
          "sha256": "4b464061a565906610ceb726205302a0ef6a5eaaf1df8da7e99297499ad67039",
          "sha1": "8341472c8b519a29af44066dd808fc323bb7f921",
          "md5": "73ff404a11b25a330e00cfb91e9ac5cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earth.headlessmc",
          "module": "headlessmc-modlauncher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "dev.xdark",
          "module": "deencapsulation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "headlessmc-launcher-wrapper-2.1.0-dev.jar",
          "url": "headlessmc-launcher-wrapper-2.1.0-dev.jar",
          "size": 8445292,
          "sha512": "059168c0cf927bd867d3690af0998eab8853afca54640be808d131c455edafc1901f3793aa4edb4bedc93cd16905824e316b9aeab444c77d0647150eb14dbf71",
          "sha256": "4b464061a565906610ceb726205302a0ef6a5eaaf1df8da7e99297499ad67039",
          "sha1": "8341472c8b519a29af44066dd808fc323bb7f921",
          "md5": "73ff404a11b25a330e00cfb91e9ac5cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-wrapper-2.1.0-sources.jar",
          "url": "headlessmc-launcher-wrapper-2.1.0-sources.jar",
          "size": 6177,
          "sha512": "064275bb033aae6fda9026a2e4bebe1b9bc82bdd893c354d54d07afbc22f1e42b2b490b293d4f897a92090682bd86cf3d5de434c1ba29749e339065cbf57c497",
          "sha256": "f9ff4a45be53bbf950223bf693398c947d973379daa13ed920677aacbc6837ba",
          "sha1": "f59ac0cbac08897306a7cfbad0ac4aad10046a93",
          "md5": "2edda2782121d0b9034945527634deae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "headlessmc-launcher-wrapper-2.1.0-javadoc.jar",
          "url": "headlessmc-launcher-wrapper-2.1.0-javadoc.jar",
          "size": 129676,
          "sha512": "bbb22d317fc67000a205530c0dacbc4d09e8cf4f3db81aa01ebfae00cfb5d9af2525b904085b2363f74cf09fa1de6ed72468417cc181dcd8ae12c963b338dc23",
          "sha256": "bc389d6220156f80a817e21a5c48dae759d727e8b73c6379a6f17b0e3da3ec53",
          "sha1": "9773ddecb2c35b91cdaa95e9d8cbf777733f572f",
          "md5": "6ceb7fc2cc89afbab5c8a291e2a5d4b9"
        }
      ]
    }
  ]
}
